'use strict';
const faker = require('faker')

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert('Events', [
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        photo: faker.random.image(),
        categoryId: 1,
        userId: 20,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        photo: faker.random.image(),
        categoryId: 1,
        userId: 23,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        photo: faker.random.image(),
        categoryId: 1,
        userId: 15,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        photo: faker.random.image(),
        categoryId: 1,
        userId: 13,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        photo: faker.random.image(),
        categoryId: 1,
        userId: 1,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        photo: faker.random.image(),
        categoryId: 2,
        userId: 2,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        photo: faker.random.image(),
        categoryId: 2,
        userId: 8,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        photo: faker.random.image(),
        categoryId: 2,
        userId: 5,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        photo: faker.random.image(),
        categoryId: 2,
        userId: 22,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        photo: faker.random.image(),
        categoryId: 2,
        userId: 16,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        photo: faker.random.image(),
        categoryId: 3,
        userId: 3,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        photo: faker.random.image(),
        categoryId: 3,
        userId: 7,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        photo: faker.random.image(),
        categoryId: 3,
        userId: 9,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        photo: faker.random.image(),
        categoryId: 3,
        userId: 11,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        photo: faker.random.image(),
        categoryId: 3,
        userId: 21,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },

    ])
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete('Events', {})
 }
};
