"use strict";
const faker = require("faker");
// const image = require('./images/thumbnail.jpg');

module.exports = {
  up: (queryInterface, Sequelize) => {
    return queryInterface.bulkInsert("Events", [
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 1,
        userId: 20,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 2,
        userId: 23,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 3,
        userId: 15,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 4,
        userId: 13,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 5,
        userId: 1,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 6,
        userId: 2,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 7,
        userId: 8,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 8,
        userId: 5,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 9,
        userId: 22,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 1,
        userId: 20,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 2,
        userId: 23,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 3,
        userId: 15,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 4,
        userId: 13,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 5,
        userId: 1,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 6,
        userId: 2,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 7,
        userId: 8,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 8,
        userId: 5,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 9,
        userId: 22,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 1,
        userId: 20,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 2,
        userId: 23,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 3,
        userId: 15,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 4,
        userId: 13,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 5,
        userId: 1,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 6,
        userId: 2,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 7,
        userId: 8,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 8,
        userId: 5,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 9,
        userId: 22,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 1,
        userId: 20,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 2,
        userId: 23,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 3,
        userId: 15,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 4,
        userId: 13,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 5,
        userId: 1,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 6,
        userId: 2,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 7,
        userId: 8,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 8,
        userId: 5,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 9,
        userId: 22,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 1,
        userId: 20,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 2,
        userId: 23,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 3,
        userId: 15,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 4,
        userId: 13,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 5,
        userId: 1,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 6,
        userId: 2,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 7,
        userId: 8,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 8,
        userId: 5,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 9,
        userId: 22,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 1,
        userId: 20,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 2,
        userId: 23,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 3,
        userId: 15,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 4,
        userId: 13,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 5,
        userId: 1,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 6,
        userId: 2,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 7,
        userId: 8,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 8,
        userId: 5,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 9,
        userId: 22,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 1,
        userId: 20,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 2,
        userId: 23,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 3,
        userId: 15,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 4,
        userId: 13,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 5,
        userId: 1,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 6,
        userId: 2,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 7,
        userId: 8,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 8,
        userId: 5,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 9,
        userId: 22,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 1,
        userId: 20,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 2,
        userId: 23,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 3,
        userId: 15,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 4,
        userId: 13,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 5,
        userId: 1,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 6,
        userId: 2,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 7,
        userId: 8,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 8,
        userId: 5,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 9,
        userId: 22,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 1,
        userId: 20,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 2,
        userId: 23,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 3,
        userId: 15,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 4,
        userId: 13,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 5,
        userId: 1,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 6,
        userId: 2,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 7,
        userId: 8,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 8,
        userId: 5,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 9,
        userId: 22,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 1,
        userId: 20,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 2,
        userId: 23,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 3,
        userId: 15,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 4,
        userId: 13,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 5,
        userId: 1,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 6,
        userId: 2,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 7,
        userId: 8,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 8,
        userId: 5,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 9,
        userId: 22,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 1,
        userId: 20,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 2,
        userId: 23,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 3,
        userId: 15,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 4,
        userId: 13,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 5,
        userId: 1,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 6,
        userId: 2,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 7,
        userId: 8,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 8,
        userId: 5,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 9,
        userId: 22,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 1,
        userId: 20,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 2,
        userId: 23,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 3,
        userId: 15,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 4,
        userId: 13,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 5,
        userId: 1,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 6,
        userId: 2,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 7,
        userId: 8,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 8,
        userId: 5,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 9,
        userId: 22,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 1,
        userId: 20,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 2,
        userId: 23,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 3,
        userId: 15,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 4,
        userId: 13,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 5,
        userId: 1,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 6,
        userId: 2,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 7,
        userId: 8,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 8,
        userId: 5,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 9,
        userId: 22,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 1,
        userId: 20,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 2,
        userId: 23,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 3,
        userId: 15,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 4,
        userId: 13,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 5,
        userId: 1,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 6,
        userId: 2,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 7,
        userId: 8,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 8,
        userId: 5,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 9,
        userId: 22,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 1,
        userId: 20,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 2,
        userId: 23,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 3,
        userId: 15,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 4,
        userId: 13,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 5,
        userId: 1,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 6,
        userId: 2,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 7,
        userId: 8,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 8,
        userId: 5,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 9,
        userId: 22,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 1,
        userId: 20,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 2,
        userId: 23,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 3,
        userId: 15,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 4,
        userId: 13,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 5,
        userId: 1,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 6,
        userId: 2,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 7,
        userId: 8,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 8,
        userId: 5,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 9,
        userId: 22,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 1,
        userId: 20,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 2,
        userId: 23,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 3,
        userId: 15,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 4,
        userId: 13,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 5,
        userId: 1,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 6,
        userId: 2,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 7,
        userId: 8,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 8,
        userId: 5,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 9,
        userId: 22,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 1,
        userId: 20,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 2,
        userId: 23,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 3,
        userId: 15,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 4,
        userId: 13,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 5,
        userId: 1,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 6,
        userId: 2,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 7,
        userId: 8,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 8,
        userId: 5,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 9,
        userId: 22,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 1,
        userId: 20,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 2,
        userId: 23,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 3,
        userId: 15,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 4,
        userId: 13,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 5,
        userId: 1,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 6,
        userId: 2,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 7,
        userId: 8,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 8,
        userId: 5,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 9,
        userId: 22,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 1,
        userId: 20,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 2,
        userId: 23,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 3,
        userId: 15,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 4,
        userId: 13,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 5,
        userId: 1,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 6,
        userId: 2,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 7,
        userId: 8,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 8,
        userId: 5,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 9,
        userId: 22,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 1,
        userId: 20,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 2,
        userId: 23,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 3,
        userId: 15,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 4,
        userId: 13,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 5,
        userId: 1,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 6,
        userId: 2,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 7,
        userId: 8,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 8,
        userId: 5,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
      {
        name: faker.random.words(3),
        description: faker.random.words(20),
        dateStart: faker.date.future(),
        dateEnd: faker.date.future(),
        categoryId: 9,
        userId: 22,
        latitude: faker.address.latitude(),
        longitude: faker.address.longitude(),
      },
    ]);
  },

  down: (queryInterface, Sequelize) => {
    return queryInterface.bulkDelete("Events", {});
  },
};
